version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: exchange_rate
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: exchange-rate-app
    restart: unless-stopped
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: exchange_rate
      EXCHANGE_RATE_API_KEY: your_api_key
      EMAIL_ADDRESS: your_email@example.com
      EMAIL_PASSWORD: your_email_password
      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
